#!/bin/sh
# ttldr: Tiny, online-only tldr client which uses tldr-fmt
# Copyright (c) 2020, Avi Halachmi (:avih) avihpit@yahoo.com
# BSD 2-Clause License - see LICENSE file

case x${1-} in x|x-*)
      [ "${1-}" = -h ] && o=1 || o=2
>&$o  echo Usage: [TT_LANG=LANG] ttldr CMD [tldr-fmt options]...
>&$o  echo Tiny, online-only tldr client. Tries CMD page in [LANG +] English.
>&$o  echo Languages: es, it, ko, pt_BR, zh, or any other at the tldr repo.
>&$o  echo Requires: curl, tldr-fmt. Home: https://github.com/avih/tldr-fmt
      [ $o = 1 ] && exit || exit
esac
cmd=$1; shift

base=https://raw.githubusercontent.com/tldr-pages/tldr/master/pages
for plat in common linux osx windows sunos; do  # from most to least pages
    for lng in ${TT_LANG-} ''; do
        curl -sf "$base${lng:+.$lng}/$plat/$cmd.md" | tldr-fmt -e1 "$@" && exit
    done
done
>&2 printf %s\\n "ttldr: page not found -- \`$cmd'" && falae
